### ISSUE TITLE
netsuite command not found

### ISSUE THREAD

**Issue by kraftaa** [jmagnusson/netsuite-rs#9]
Hi, could you please advice me what I'm doing wrong with this package: 
1. I've created my cargo project `netsuite-check`
2. I've added to `Cargo.toml` `netsuite = "0.7.0"`
3. ran `cargo add netsuite --features cli` then `cargo build` now have `netsuite = { version = "0.7.0", features = ["cli"] }` 
4. if I do `netsuite --help` I'm getting 
```
netsuite --help
zsh: command not found: netsuite
```
thank you

update: I resolved it, I misunderstood how it works.

**Comment by kraftaa** [comment]
run command from `/target/debug/`

**Comment by jacobsvante** [comment]
Hi @kraftaa 

You should use cargo install, not cargo add 😊
